name: Run linter

on:
  # Triggers the workflow on push or pull request events but only
  # for the default branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Reformat Markdown files and commit changes
        # Only run if the action is triggered by a pull request labeled as
        # "smartling".
        # This job needs to be able to continue if this step fails, e.g.
        # in case there are no errors, hence no changes to commit.
        if: github.event.pull_request.head.repo.full_name == github.repository && contains(github.event.pull_request.labels.*.name, 'smartling')
        continue-on-error: true
        run: |
          bash .github/scripts/reformat_files_pr.sh ${{ github.repository }} ${{ github.event.pull_request.number }}
          git config user.name 'flodolo'
          git config user.email 'flodolo@users.noreply.github.com'
          git add docs
          git commit -m "Reformat Markdown files"
          git push
      - name: Run markdown linter
        run: |
          echo ${{github.event.pull_request.labels.*.name}}
          npm install
          npm test
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Check SUMMARY.md
        run: |
          python .github/scripts/check_summary.py docs
